services:
  postgres:
    image: postgres:18.0-alpine3.22
    container_name: express_boilerplate_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgbouncer:
    image: edoburu/pgbouncer:v1.24.1-p0
    environment:
      POOL_MODE: session
      MAX_CLIENT_CONN: 100
      DEFAULT_POOL_SIZE: 20
      AUTH_TYPE: scram-sha-256
    ports:
      - "5432:5432"
    depends_on:
      - postgres
